// The wallet's message catalog, in Chrome's own format.
//
//   node scripts/i18n.mjs build    # public/_locales/en/messages.json -> src/i18n/en.generated.ts
//   node scripts/i18n.mjs check    # every key used is defined, every key defined is used,
//                                  # every locale has every key; exit 1 otherwise
//   node scripts/i18n.mjs review <locale> [--machine] > review-<locale>.md
//
// `en/messages.json` is the source of truth. Each entry carries the message
// and a `description` naming where it appears and what any `$1` stands for,
// which is what a translator reads. A locale file has the same keys and only
// `message` (Chrome reads nothing else). The keys a draft wrote and nobody
// has checked are listed in `src/i18n/status/<locale>.json` under "machine";
// a reviewer removes what they have read. That list lives outside
// `public/` so it is never packaged.
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const LOCALES_DIR = join(ROOT, 'public', '_locales');
const SRC = join(ROOT, 'src');
const GENERATED = join(SRC, 'i18n', 'en.generated.ts');
const STATUS_DIR = join(SRC, 'i18n', 'status');
const [command, locale, ...flags] = process.argv.slice(2);

const readJson = (path, fallback) => (existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : fallback);
const en = readJson(join(LOCALES_DIR, 'en', 'messages.json'), {});
const locales = existsSync(LOCALES_DIR)
  ? readdirSync(LOCALES_DIR).filter((name) => name !== 'en' && statSync(join(LOCALES_DIR, name)).isDirectory())
  : [];

function* sourceFiles(dir) {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) {
      if (name === '__tests__' || name === 'i18n') continue;
      yield* sourceFiles(path);
    } else if (/\.tsx?$/.test(name) && !/\.test\.tsx?$/.test(name)) yield path;
  }
}

/** Every `t('key')` / `t("key")` call site in src, key -> files. */
function usedKeys() {
  const CALL = /\bt\(\s*(?:'([A-Za-z0-9_]+)'|"([A-Za-z0-9_]+)")/g;
  const found = new Map();
  for (const file of sourceFiles(SRC)) {
    const text = readFileSync(file, 'utf8');
    for (const match of text.matchAll(CALL)) {
      const key = match[1] ?? match[2];
      const list = found.get(key) ?? [];
      list.push(relative(SRC, file).replace(/\\/g, '/'));
      found.set(key, list);
    }
  }
  return found;
}

function build() {
  const keys = Object.keys(en).sort((a, b) => a.localeCompare(b));
  const lines = [
    '// Generated by `node scripts/i18n.mjs build` from public/_locales/en/messages.json. Do not edit.',
    '// The English catalog as a type, so a call site cannot name a message that does not exist, and',
    '// as a value, so unit tests outside an extension context read the English copy.',
    'export const EN = {',
    ...keys.map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(en[key].message)},`),
    '} as const;',
    '',
    'export type MessageKey = keyof typeof EN;',
    '',
  ];
  writeFileSync(GENERATED, lines.join('\n'));
  console.log(`en.generated.ts: ${keys.length} messages`);
}

function check() {
  let failed = false;
  const used = usedKeys();
  const defined = new Set(Object.keys(en));
  // Read by the manifest and by src/i18n itself (which the call-site scan skips), never by a page.
  const platformKeys = new Set(['appName', 'appDescription', 'appLocale']);
  const undefinedKeys = [...used.keys()].filter((key) => !defined.has(key));
  const unusedKeys = [...defined].filter((key) => !used.has(key) && !platformKeys.has(key));
  if (undefinedKeys.length) {
    failed = true;
    console.error(`used but not defined in en/messages.json (${undefinedKeys.length}):`);
    for (const key of undefinedKeys) console.error(`  ${key}  ${used.get(key).join(', ')}`);
  }
  if (unusedKeys.length) {
    failed = true;
    console.error(`defined but never used (${unusedKeys.length}):`);
    for (const key of unusedKeys) console.error(`  ${key}`);
  }
  for (const name of locales) {
    const messages = readJson(join(LOCALES_DIR, name, 'messages.json'), {});
    const missing = [...defined].filter((key) => !(key in messages));
    const extra = Object.keys(messages).filter((key) => !defined.has(key));
    const badPlaceholders = [...defined].filter((key) => {
      if (!(key in messages)) return false;
      const want = (en[key].message.match(/\$\d/g) ?? []).sort().join('');
      const have = (messages[key].message.match(/\$\d/g) ?? []).sort().join('');
      return want !== have;
    });
    const status = readJson(join(STATUS_DIR, `${name}.json`), { machine: [] });
    const staleStatus = status.machine.filter((key) => !defined.has(key));
    if (missing.length || extra.length || badPlaceholders.length || staleStatus.length) failed = true;
    console.log(`${name}: ${Object.keys(messages).length} messages, missing ${missing.length}, stale ${extra.length}, placeholder mismatches ${badPlaceholders.length}, ${status.machine.length} awaiting review`);
    for (const key of staleStatus) console.log(`  status lists a key that no longer exists: ${key}`);
    for (const key of missing.slice(0, 20)) console.log(`  missing ${key}`);
    for (const key of extra) console.log(`  stale ${key}`);
    for (const key of badPlaceholders) console.log(`  placeholders ${key}: en "${en[key].message}" vs "${messages[key].message}"`);
  }
  const generated = existsSync(GENERATED) ? readFileSync(GENERATED, 'utf8') : '';
  const generatedKeys = [...generated.matchAll(/^  "([^"]+)":/gm)].map((m) => m[1]);
  if (generatedKeys.join('\n') !== [...defined].sort((a, b) => a.localeCompare(b)).join('\n')) {
    failed = true;
    console.error('src/i18n/en.generated.ts is out of date; run `node scripts/i18n.mjs build`');
  }
  console.log(`en: ${defined.size} messages, ${used.size} used at ${[...used.values()].flat().length} call sites`);
  process.exit(failed ? 1 : 0);
}

function review() {
  if (!locale) {
    console.error('usage: node scripts/i18n.mjs review <locale> [--machine]');
    process.exit(2);
  }
  const messages = readJson(join(LOCALES_DIR, locale, 'messages.json'), {});
  const status = readJson(join(STATUS_DIR, `${locale}.json`), { machine: [] });
  const machine = new Set(status.machine);
  const onlyMachine = flags.includes('--machine');
  const used = usedKeys();
  const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
  const keys = Object.keys(messages).filter((key) => !onlyMachine || machine.has(key));
  console.log(`# ${locale}: ${keys.length} strings${onlyMachine ? ' awaiting review' : ''}\n`);
  console.log(`| | English | ${locale} | Where | Meaning |`);
  console.log('|---|---|---|---|---|');
  for (const key of keys) {
    const where = (used.get(key) ?? []).map((f) => f.replace(/\.tsx?$/, '')).join(', ');
    console.log(`| ${machine.has(key) ? '🤖' : '✅'} | ${esc(en[key]?.message ?? '')} | ${esc(messages[key].message)} | ${esc(where)} | ${esc(en[key]?.description ?? '')} |`);
  }
}

if (command === 'build') build();
else if (command === 'check') check();
else if (command === 'review') review();
else {
  console.error('usage: node scripts/i18n.mjs <build|check|review>');
  process.exit(2);
}
