// The wallet's message catalog, in Chrome's own format.
//
//   node scripts/i18n.mjs build    # public/_locales/en/messages.json -> src/i18n/en.generated.ts
//   node scripts/i18n.mjs check    # every key used is defined, every key defined is used,
//                                  # every locale has every key, and no number is
//                                  # formatted in a language nobody chose; exit 1 otherwise
//   node scripts/i18n.mjs review <locale> [--machine] > review-<locale>.md
//
// `en/messages.json` is the source of truth. Each entry carries the message
// and a `description` naming where it appears and what any `$1` stands for,
// which is what a translator reads. A locale file has the same keys and only
// `message` (Chrome reads nothing else). The keys a draft wrote and nobody
// has checked are listed in `src/i18n/status/<locale>.json` under "machine";
// a reviewer removes what they have read. That list lives outside
// `public/` so it is never packaged.
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join, relative } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1');
const LOCALES_DIR = join(ROOT, 'public', '_locales');
const SRC = join(ROOT, 'src');
const GENERATED = join(SRC, 'i18n', 'en.generated.ts');
const STATUS_DIR = join(SRC, 'i18n', 'status');
const [command, locale, ...flags] = process.argv.slice(2);

const readJson = (path, fallback) => (existsSync(path) ? JSON.parse(readFileSync(path, 'utf8')) : fallback);
const en = readJson(join(LOCALES_DIR, 'en', 'messages.json'), {});
const locales = existsSync(LOCALES_DIR)
  ? readdirSync(LOCALES_DIR).filter((name) => name !== 'en' && statSync(join(LOCALES_DIR, name)).isDirectory())
  : [];

function* sourceFiles(dir) {
  for (const name of readdirSync(dir)) {
    const path = join(dir, name);
    if (statSync(path).isDirectory()) {
      if (name === '__tests__' || name === 'i18n') continue;
      yield* sourceFiles(path);
    } else if (/\.tsx?$/.test(name) && !/\.test\.tsx?$/.test(name)) yield path;
  }
}

/** Every `t('key')` / `t("key")` call site in src, key -> files. */
function usedKeys() {
  const CALL = /\bt\(\s*(?:'([A-Za-z0-9_]+)'|"([A-Za-z0-9_]+)")/g;
  const found = new Map();
  for (const file of sourceFiles(SRC)) {
    const text = readFileSync(file, 'utf8');
    for (const match of text.matchAll(CALL)) {
      const key = match[1] ?? match[2];
      const list = found.get(key) ?? [];
      list.push(relative(SRC, file).replace(/\\/g, '/'));
      found.set(key, list);
    }
  }
  return found;
}

// Chrome treats $1$2 as the named variable $1$, not two positional values.
// Named placeholders also allow adjacent substitutions without inserting visible whitespace.
const expandedMessage = entry => entry.message.replace(/\$([A-Za-z0-9_]+)\$/g,
  (match, name) => entry.placeholders?.[name.toLowerCase()]?.content ?? match);

function generatedSource() {
  const keys = Object.keys(en).sort((a, b) => a.localeCompare(b));
  const lines = [
    '// Generated by `node scripts/i18n.mjs build` from public/_locales/en/messages.json. Do not edit.',
    '// The English catalog as a type, so a call site cannot name a message that does not exist, and',
    '// as a value, so unit tests outside an extension context read the English copy.',
    'export const EN = {',
    ...keys.map((key) => `  ${JSON.stringify(key)}: ${JSON.stringify(expandedMessage(en[key]))},`),
    '} as const;',
    '',
    'export type MessageKey = keyof typeof EN;',
    '',
  ];
  return lines.join('\n');
}

function build() {
  writeFileSync(GENERATED, generatedSource());
  console.log(`en.generated.ts: ${Object.keys(en).length} messages`);
}

/**
 * Numbers formatted in a language nobody chose.
 *
 * The catalog check above cannot see these: a number is not a message, so a
 * figure written in the wrong language is invisible to every count on this
 * page. Two shapes are wrong, for different reasons.
 *
 * A locale pinned to English renders 1.234,56 as 1,234.56 on a page that is
 * not in English. And no locale at all is worse than it looks: `Intl` then
 * follows the browser's REGIONAL FORMAT setting while every word on screen
 * came from its UI LANGUAGE, and a reader can have those disagree — Japanese
 * chrome around English digits, or the reverse.
 *
 * The fix for both is `formatAmount` from core/format, which resolves the
 * language the wallet is actually reading in. The exception is a value bound
 * for an input field, which must stay machine-formatted and has its own
 * function: `formatForInput`.
 *
 * A site that genuinely must pin a locale says so with `i18n-number-ok` on
 * the line or the one above it.
 */
const NUMBER_RULES = [
  [/\.toLocale(?:String|DateString|TimeString)\(\s*\)/g, 'no locale at all: follows the browser\'s regional format, not the wallet\'s language'],
  [/(?:toLocale(?:String|DateString|TimeString)|Intl\.[A-Za-z]+)\(\s*['"]en(?:-[A-Z]{2})?['"]/g, 'pinned to English on a page that is not always English'],
];

function numbersInNoLanguage() {
  const findings = [];
  for (const file of sourceFiles(SRC)) {
    const rel = relative(SRC, file).replace(/\\/g, '/');
    // core/format.ts is where the default is decided, so it is the one file
    // allowed to name a locale.
    if (rel === 'core/format.ts') continue;
    const text = readFileSync(file, 'utf8');
    const lines = text.split(/\r?\n/);
    // Scan the code, not the prose. A doc comment explaining why a bare
    // toLocaleString is wrong necessarily contains one, and a checker that
    // cannot tell the difference teaches people to stop writing the
    // explanation. Comments become spaces, so every offset still lines up.
    const code = text
      .replace(/\/\*[\s\S]*?\*\//g, (m) => m.replace(/[^\n]/g, ' '))
      .replace(/\/\/[^\n]*/g, (m) => ' '.repeat(m.length));
    for (const [pattern, why] of NUMBER_RULES) {
      for (const match of code.matchAll(pattern)) {
        const at = code.slice(0, match.index).split('\n').length;
        const here = lines[at - 1] ?? '';
        const above = lines[at - 2] ?? '';
        if (here.includes('i18n-number-ok') || above.includes('i18n-number-ok')) continue;
        findings.push(`  ${rel}:${at}  ${why}`);
      }
    }
  }
  return findings;
}

/**
 * Approval fact labels that would wrap.
 *
 * A fact row gives its label the space the value leaves, so a label longer than the budget
 * breaks onto a second line at popup width, and in Japanese or Chinese it breaks mid-word. The
 * budget for a row label is 18 half-width units at 350px (18 Latin characters, or 9 full-width
 * ones, which count double) and 28 in the side panel; every approval can open in the popup, so
 * the popup budget is the one enforced. A label that sits on its own line above its value (a
 * headline amount, a paragraph, an address) has the whole line, and gets twice the budget.
 * Kept in step with src/components/domain/approval/fact-layout.ts; the approval galleries assert
 * the same thing on the rendered screens.
 *
 * Label keys are found where approval facts are built: a `label:` property built from
 * `t('key')` in the Counterparty review producers and approval surfaces, a `label={t('key')}`
 * prop on an approval surface, and the English label sources the protocol describer passes
 * through tx-action-info's localizer.
 */
const LABEL_BUDGET = 18;
const STACKED_LABEL_BUDGET = 36;
const FULL_WIDTH = /[\u1100-\u115F\u2E80-\uA4CF\uAC00-\uD7A3\uF900-\uFAFF\uFE30-\uFE4F\uFF00-\uFF60\uFFE0-\uFFE6]/u;
/** A substituted value (an asset name, a count) is assumed to be four units wide. */
const displayWidth = (text) => [...text.replace(/\$\d/g, 'XXXX')].reduce((width, char) => width + (FULL_WIDTH.test(char) ? 2 : 1), 0);
const STACKED = /'(?:paragraph|address|outpoint|identifier)'|emphasis:\s*'primary'|layout:\s*'stacked'/;

/** The text of the call or object literal that opens at `from`, up to its closing bracket. */
function balanced(text, from) {
  let depth = 0;
  for (let at = from; at < text.length; at += 1) {
    const char = text[at];
    if (char === '(' || char === '[' || char === '{') depth += 1;
    else if (char === ')' || char === ']' || char === '}') { depth -= 1; if (depth === 0) return text.slice(from, at + 1); }
  }
  return text.slice(from);
}

/** Label key -> true when every use stacks it on its own line (one row use keeps the row budget). */
function factLabelKeys() {
  const rows = new Set();
  const stacked = new Set();
  const note = (key, isStacked) => (isStacked ? stacked : rows).add(key);
  const PRODUCERS = ['core/counterparty/', 'components/domain/approval/', 'pages/requests/'];
  for (const file of sourceFiles(SRC)) {
    const rel = relative(SRC, file).replace(/\\/g, '/');
    if (!PRODUCERS.some((prefix) => rel.startsWith(prefix))) continue;
    const text = readFileSync(file, 'utf8');
    for (const match of text.matchAll(/\blabel:([\s\S]{0,240}?)\bvalue:/g)) {
      const open = text.lastIndexOf('{', match.index);
      const object = open >= 0 ? balanced(text, open) : match[0];
      for (const [, key] of match[1].matchAll(/\bt\(\s*'([A-Za-z0-9_]+)'/g)) note(key, STACKED.test(object));
    }
    for (const [, key] of text.matchAll(/\blabel=\{t\(\s*'([A-Za-z0-9_]+)'/g)) note(key, false);
  }
  // The describer labels in English and tx-action-info maps each source string to its key.
  const describePath = join(SRC, 'core', 'counterparty', 'describe.ts');
  const localizerPath = join(SRC, 'components', 'domain', 'tx', 'tx-action-info.ts');
  const describe = existsSync(describePath) ? readFileSync(describePath, 'utf8') : '';
  const localizer = existsSync(localizerPath) ? readFileSync(localizerPath, 'utf8') : '';
  const keyFor = new Map([...localizer.matchAll(/case "((?:[^"\\]|\\.)*)": return t\('([A-Za-z0-9_]+)'/g)].map(([, source, key]) => [source, key]));
  const sources = [['Memo', true]];
  for (const match of describe.matchAll(/\badd(?:Memo)?\(/g)) {
    const call = balanced(describe, match.index + match[0].length - 1);
    // The first argument, up to its top-level comma; every string literal in it is a label source.
    let depth = 0;
    let end = 1;
    for (; end < call.length; end += 1) {
      const char = call[end];
      if (char === '(' || char === '[' || char === '{') depth += 1;
      else if (char === ')' || char === ']' || char === '}') { if (depth === 0) break; depth -= 1; }
      else if (char === ',' && depth === 0) break;
    }
    const isStacked = match[0] === 'addMemo(' || STACKED.test(call);
    for (const [, source] of call.slice(1, end).matchAll(/'([^'\n]+)'/g)) sources.push([source, isStacked]);
  }
  for (const match of describe.matchAll(/\blabel:\s*text\('([^'\n]+)'/g)) {
    const open = describe.lastIndexOf('{', match.index);
    sources.push([match[1], STACKED.test(balanced(describe, open))]);
  }
  for (const [source, isStacked] of sources) if (keyFor.has(source)) note(keyFor.get(source), isStacked);
  const keys = new Map();
  for (const key of [...rows, ...stacked].sort()) if (key in en) keys.set(key, !rows.has(key));
  return keys;
}

function labelsOverBudget() {
  const findings = [];
  const keys = factLabelKeys();
  for (const name of ['en', ...locales]) {
    const catalog = readJson(join(LOCALES_DIR, name, 'messages.json'), {});
    for (const [key, isStacked] of keys) {
      if (!catalog[key]) continue;
      const label = expandedMessage(catalog[key]);
      const width = displayWidth(label);
      const budget = isStacked ? STACKED_LABEL_BUDGET : LABEL_BUDGET;
      if (width > budget) findings.push(`  ${name}: ${key} "${label}" is ${width} units, budget ${budget}${isStacked ? ' (own line)' : ''}`);
    }
  }
  return { keys, findings };
}

function check() {
  let failed = false;
  const used = usedKeys();
  const defined = new Set(Object.keys(en));
  // Read by the manifest and by src/i18n itself (which the call-site scan skips), never by a page.
  const platformKeys = new Set(['appName', 'appDescription', 'appLocale']);
  const undefinedKeys = [...used.keys()].filter((key) => !defined.has(key));
  const unusedKeys = [...defined].filter((key) => !used.has(key) && !platformKeys.has(key));
  if (undefinedKeys.length) {
    failed = true;
    console.error(`used but not defined in en/messages.json (${undefinedKeys.length}):`);
    for (const key of undefinedKeys) console.error(`  ${key}  ${used.get(key).join(', ')}`);
  }
  if (unusedKeys.length) {
    failed = true;
    console.error(`defined but never used (${unusedKeys.length}):`);
    for (const key of unusedKeys) console.error(`  ${key}`);
  }
  for (const name of locales) {
    const messages = readJson(join(LOCALES_DIR, name, 'messages.json'), {});
    const missing = [...defined].filter((key) => !(key in messages));
    const extra = Object.keys(messages).filter((key) => !defined.has(key));
    const badPlaceholders = [...defined].filter((key) => {
      if (!(key in messages)) return false;
      const want = (expandedMessage(en[key]).match(/\$\d/g) ?? []).sort().join('');
      const have = (expandedMessage(messages[key]).match(/\$\d/g) ?? []).sort().join('');
      return want !== have;
    });
    const status = readJson(join(STATUS_DIR, `${name}.json`), { machine: [] });
    const staleStatus = status.machine.filter((key) => !defined.has(key));
    if (missing.length || extra.length || badPlaceholders.length || staleStatus.length) failed = true;
    console.log(`${name}: ${Object.keys(messages).length} messages, missing ${missing.length}, stale ${extra.length}, placeholder mismatches ${badPlaceholders.length}, ${status.machine.length} awaiting review`);
    for (const key of staleStatus) console.log(`  status lists a key that no longer exists: ${key}`);
    for (const key of missing.slice(0, 20)) console.log(`  missing ${key}`);
    for (const key of extra) console.log(`  stale ${key}`);
    for (const key of badPlaceholders) console.log(`  placeholders ${key}: en "${en[key].message}" vs "${messages[key].message}"`);
  }
  for (const name of ['en', ...locales]) {
    const catalog = readJson(join(LOCALES_DIR, name, 'messages.json'), {});
    for (const [key, entry] of Object.entries(catalog)) {
      for (const [, variable] of entry.message.matchAll(/\$([A-Za-z0-9_]+)\$/g)) {
        if (!entry.placeholders?.[variable.toLowerCase()]) {
          console.error(`${name}: ${key} references undefined Chrome placeholder $${variable}$`);
          failed = true;
        }
      }
    }
  }
  const labels = labelsOverBudget();
  if (labels.findings.length) {
    failed = true;
    console.error(`approval fact labels over budget at popup width (${labels.findings.length}; full-width characters count 2):`);
    for (const line of labels.findings) console.error(line);
  }
  console.log(`approval fact labels: ${labels.keys.size} keys measured (row ${LABEL_BUDGET}, own line ${STACKED_LABEL_BUDGET} units)`);
  const numbers = numbersInNoLanguage();
  if (numbers.length) {
    failed = true;
    console.error(`numbers formatted in a language nobody chose (${numbers.length}):`);
    for (const line of numbers) console.error(line);
  }
  const generated = existsSync(GENERATED) ? readFileSync(GENERATED, 'utf8') : '';
  if (generated.replace(/\r\n/g, '\n') !== generatedSource()) {
    failed = true;
    console.error('src/i18n/en.generated.ts is out of date; run `node scripts/i18n.mjs build`');
  }
  console.log(`en: ${defined.size} messages, ${used.size} used at ${[...used.values()].flat().length} call sites`);
  process.exit(failed ? 1 : 0);
}

function review() {
  if (!locale) {
    console.error('usage: node scripts/i18n.mjs review <locale> [--machine]');
    process.exit(2);
  }
  const messages = readJson(join(LOCALES_DIR, locale, 'messages.json'), {});
  const status = readJson(join(STATUS_DIR, `${locale}.json`), { machine: [] });
  const machine = new Set(status.machine);
  const onlyMachine = flags.includes('--machine');
  const used = usedKeys();
  const esc = (s) => String(s).replace(/\\/g, '\\\\').replace(/\|/g, '\\|').replace(/[\r\n]/g, ' ');
  const keys = Object.keys(messages).filter((key) => !onlyMachine || machine.has(key));
  console.log(`# ${locale}: ${keys.length} strings${onlyMachine ? ' awaiting review' : ''}\n`);
  console.log(`| | English | ${locale} | Where | Meaning |`);
  console.log('|---|---|---|---|---|');
  for (const key of keys) {
    const where = (used.get(key) ?? []).map((f) => f.replace(/\.tsx?$/, '')).join(', ');
    console.log(`| ${machine.has(key) ? '🤖' : '✅'} | ${esc(en[key]?.message ?? '')} | ${esc(messages[key].message)} | ${esc(where)} | ${esc(en[key]?.description ?? '')} |`);
  }
}

if (command === 'build') build();
else if (command === 'check') check();
else if (command === 'review') review();
else {
  console.error('usage: node scripts/i18n.mjs <build|check|review>');
  process.exit(2);
}
