name: Publish Extension

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Perform a dry run without actually submitting'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      publish_chrome:
        description: 'Publish to Chrome Web Store'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      publish_firefox:
        description: 'Publish to Firefox Add-on Store'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build extension
        run: npm run build

      - name: Create ZIP for Chrome
        if: inputs.publish_chrome == 'true'
        run: npm run zip

      - name: Create ZIP for Firefox
        if: inputs.publish_firefox == 'true'
        run: npm run zip:firefox

      - name: List output files
        run: ls -la .output/

      - name: Submit to stores (Dry Run)
        if: inputs.dry_run == 'true'
        run: |
          FLAGS="--dry-run"
          
          if [[ "${{ inputs.publish_chrome }}" == "true" ]]; then
            FLAGS="$FLAGS --chrome-zip .output/*-chrome.zip"
          fi
          
          if [[ "${{ inputs.publish_firefox }}" == "true" ]]; then
            FLAGS="$FLAGS --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip"
          fi
          
          npx wxt submit $FLAGS
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}

      - name: Submit to stores
        if: inputs.dry_run == 'false'
        run: |
          FLAGS=""
          
          if [[ "${{ inputs.publish_chrome }}" == "true" ]]; then
            FLAGS="$FLAGS --chrome-zip .output/*-chrome.zip"
          fi
          
          if [[ "${{ inputs.publish_firefox }}" == "true" ]]; then
            FLAGS="$FLAGS --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip"
          fi
          
          npx wxt submit $FLAGS
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extension-packages
          path: .output/*.zip
          retention-days: 30